const gpu = [
  {
    id: 'rx79xtx',
    name: 'XFX MERC 310 AMD Radeon RX 7900 XTX Black',
    price: 11990,
    url: 'https://www.komplett.no/product/1221500/datautstyr/pc-komponenter/skjermkort/xfx-merc-310-amd-radeon-rx-7900-xtx-black?gad_campaignid=20188016872',
    info: 'High-end AMD GPU suitable for 4K gaming and content creation.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: '4K gaming / content creators',
    image: './imgas/GPU/rx79xtx.jpg'
  },
  {
    id: 'gt1030',
    name: 'ASUS Geforce GT 1030 2GB Silent',
    price: 1135,
    url: 'https://www.komplett.no/product/921791/datautstyr/pc-komponenter/skjermkort/asus-geforce-gt-1030-2gb-silent',
    info: 'Entry-level GPU ideal for casual gaming and HTPC setups.',
    type: 'GPU',
    tier: 'entry',
    bestFor: 'Casual gaming / media PCs',
    image: './imgas/GPU/gt1030.jpg'
  },
  {
    id: 'rtx5090',
    name: 'ASUS ROG Astral GeForce RTX 5090 OC',
    price: 36990,
    url: 'https://www.komplett.no/product/1319715/datautstyr/pc-komponenter/skjermkort/asus-rog-astral-lc-geforce-rtx-5090-oc?gad_campaignid=20188016872',
    info: 'Extreme performance GPU for 4K/8K gaming and professional workloads.',
    type: 'GPU',
    tier: 'enthusiast',
    bestFor: 'Ultimate gaming / workstation',
    image: './imgas/GPU/rtx5090.jpg'
  },
  {
    id: 'rtx5080tuf',
    name: 'ASUS TUF Gaming GeForce RTX 5080 OC',
    price: 15999,
    url: 'https://www.komplett.no/product/1318012/datautstyr/pc-komponenter/skjermkort/asus-tuf-gaming-geforce-rtx-5080-oc?gad_campaignid=20188016872',
    info: 'High-performance GPU with robust cooling and overclocking headroom.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: 'High-resolution gaming / overclocking',
    image: './imgas/GPU/rtx5080tuf.jpg'
  },
  {
    id: 'rtx4060ventus',
    name: 'MSI GeForce RTX 4060 Ventus 2X Black OC',
    price: 3790,
    url: 'https://www.komplett.no/product/1247758/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-4060-ventus-2x-black-oc?gad_campaignid=20188016872',
    info: 'Mid-range GPU perfect for 1080p and light 1440p gaming.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1080p / 1440p gaming',
    image: '/imgas/GPU/rtx4060ventus.jpg'
  },
  {
    id: 'rtx5070prime',
    name: 'ASUS Prime GeForce RTX 5070 OC',
    price: 7299,
    url: 'https://www.komplett.no/product/1321177/datautstyr/pc-komponenter/skjermkort/asus-prime-geforce-rtx-5070-oc?gad_campaignid=20188016872',
    info: 'Solid performance GPU for 1440p gaming with good cooling.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1440p gaming',
    image: './imgas/GPU/rtx5070prime.jpg'
  },
  {
    id: 'rtx5080astral',
    name: 'ASUS ROG Astral GeForce RTX 5080 Gaming OC',
    price: 19490,
    url: 'https://www.komplett.no/product/1318014/datautstyr/pc-komponenter/skjermkort/asus-rog-astral-geforce-rtx-5080-gaming-oc?gad_campaignid=20188016872',
    info: 'High-end GPU for demanding games at high resolutions.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: '1440p / 4K gaming',
    image: './imgas/GPU/rtx5080astral.jpg'
  },
  {
    id: 'rx9070prime',
    name: 'ASUS Prime AMD Radeon RX 9070 OC',
    price: 7990,
    url: 'https://www.komplett.no/product/1318735/datautstyr/pc-komponenter/skjermkort/asus-prime-amd-radeon-rx-9070-oc',
    info: 'Strong AMD GPU for 1440p gaming and general content creation.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1440p gaming / creative work',
    image: './imgas/GPU/rx9070prime.jpg'
  },
  {
    id: 'rtx3050dual',
    name: 'ASUS Dual GeForce RTX 3050 V2 OC',
    price: 2816,
    url: 'https://www.komplett.no/product/1303224/datautstyr/pc-komponenter/skjermkort/asus-dual-geforce-rtx-3050-oc',
    info: 'Entry-level 1080p GPU with low power draw and quiet cooling.',
    type: 'GPU',
    tier: 'entry',
    bestFor: '1080p gaming / budget builds',
    image: './imgas/GPU/rtx3050dual.jpg'
  },
  {
    id: 'rtx5060titurf',
    name: 'Asus TUF GeForce RTX 5060 Ti GAMING OC',
    price: 6489,
    url: 'https://www.kstsomplett.no/product/1322681/datautstyr/pc-komponenter/skjermkort/asus-tuf-geforce-rtx-5060-ti-gaming-oc?gad_campaignid=20188016872',
    info: 'Mid-range GPU with good cooling for consistent 1080p/1440p gaming.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1080p / 1440p gaming',
    image: './imgas/GPU/rtx5060titurf.jpg'
  },
  {
    id: 'rtx5070tuf',
    name: 'ASUS TUF Gaming GeForce RTX 5070 OC',
    price: 9490,
    url: '',
    info: 'Reliable GPU for 1440p gaming with stable performance.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1440p gaming',
    image: './imgas/GPU/rtx5070tuf.jpg'
  },
  {
    id: 'rtx5090phantom',
    name: 'Gainward GeForce RTX 5090 Phantom GS',
    price: 33990,
    url: 'https://www.komplett.no/product/1321178/datautstyr/pc-komponenter/skjermkort/asus-tuf-gaming-geforce-rtx-5070-oc?gad_campaignid=20188016872',
    info: 'Top-tier GPU for extreme gaming and professional workloads.',
    type: 'GPU',
    tier: 'enthusiast',
    bestFor: 'Ultimate gaming / workstation',
    image: './imgas/GPU/rtx5090suprim.jpg'
  },
  {
    id: 'arcb580',
    name: 'SPARKLE Intel Arc B580 TITAN OC',
    price: 3590,
    url: 'https://www.komplett.no/product/1317265/datautstyr/pc-komponenter/skjermkort/asrock-intel-arc-b580-steel-legend-oc?gad_campaignid=20188016872',
    info: 'Intel Arc GPU for light gaming and productivity at 1080p.',
    type: 'GPU',
    tier: 'entry',
    bestFor: '1080p gaming / office setups',
    image: './imgas/GPU/arcb580.jpg'
  },
  {
    id: 'rtx3050phoenix',
    name: 'ASUS GeForce RTX 3050 Phoenix V2',
    price: 2990,
    url: 'https://www.komplett.no/product/1225335/datautstyr/pc-komponenter/skjermkort/asus-geforce-rtx-3050-phoenix-v2',
    info: 'Entry-level GPU optimized for 1080p gaming.',
    type: 'GPU',
    tier: 'entry',
    bestFor: '1080p gaming',
    image: './imgas/GPU/rtx3050phoenix.jpg'
  },
  {
    id: 'rtx5080trio',
    name: 'MSI GeForce RTX 5080 GAMING TRIO OC',
    price: 16888,
    url: 'https://www.komplett.no/product/1319045/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5080-gaming-trio-oc?gad_campaignid=20188016872',
    info: 'High-end GPU with excellent cooling and overclocking potential.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: '1440p / 4K gaming',
    image: './imgas/GPU/rtx5080trio.jpg'
  },
  {
    id: 'rtx5060prime',
    name: 'ASUS PRIME GeForce RTX 5060 Ti OC',
    price: 5990,
    url: '',
    info: 'Solid mid-range GPU for smooth 1080p/1440p gaming.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1080p / 1440p gaming',
    image: './imgas/GPU/rtx5060prime.jpg'
  },
  {
    id: 'rtx5090lc',
    name: 'Asus ROG Astral LC GeForce RTX 5090 OC',
    price: 32990,
    url: 'https://www.komplett.no/product/1322680/datautstyr/pc-komponenter/skjermkort/asus-prime-geforce-rtx-5060-ti-oc?gad_campaignid=20188016872',
    info: 'Top-tier GPU with liquid cooling for extreme performance.',
    type: 'GPU',
    tier: 'enthusiast',
    bestFor: 'Ultimate gaming / workstation',
    image: './imgas/GPU/rtx5090lc.jpg'
  },
  {
    id: 'rtx5070python',
    name: 'Gainward GeForce RTX 5070 Python III',
    price: 7787,
    url: 'https://www.komplett.no/product/1321295/datautstyr/pc-komponenter/skjermkort/gainward-geforce-rtx-5070-python-iii?gad_campaignid=20188016872',
    info: 'Mid-range GPU suitable for 1440p gaming with efficient cooling.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1440p gaming',
    image: './imgas/GPU/rtx5070python.jpg'
  },
  {
    id: 'rx9070xt',
    name: 'ASRock AMD Radeon RX 9070 XT Taichi OC',
    price: 9999,
    url: 'https://www.komplett.no/product/1321210/datautstyr/pc-komponenter/skjermkort/xfx-quicksilver-amd-radeon-rx-9070-xt-gaming-hvit?gad_campaignid=20188016872',
    info: 'High-end AMD GPU for 1440p/4K gaming and content creation.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: '4K gaming / content creation',
    image: './imgas/GPU/rx9070xt.jpg'
  },
  {
    id: 'rx9060dual',
    name: 'Asus Dual Radeon RX 9060 XT',
    price: 3795,
    url: 'https://www.komplett.no/product/1324037/datautstyr/pc-komponenter/skjermkort/asus-dual-radeon-rx-9060-xt?gad_campaignid=1601331773',
    info: 'Mid-range AMD GPU suitable for 1080p/1440p gaming.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1080p / 1440p gaming',
    image: './imgas/GPU/rx9060dual.jpg'
  },
  {
    id: 'rtx5080liquid',
    name: 'MSI GeForce RTX 5080 SUPRIM LIQUID SOC',
    price: 18125,
    url: 'https://www.komplett.no/product/1319048/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5080-suprim-liquid-soc?gad_campaignid=20188016872',
    info: 'High-end GPU with liquid cooling for sustained high performance.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: '1440p / 4K gaming',
    image: './imgas/GPU/rtx5080liquid.jpg'
  },
  {
    id: 'rtx5080ventus',
    name: 'MSI GeForce RTX 5080 VENTUS 3X OC PLUS',
    price: 13640,
    url: 'https://www.komplett.no/product/1319049/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5080-ventus-3x-oc-hvit?gad_campaignid=20188016872',
    info: 'High-performance GPU for smooth high-resolution gaming.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: '1440p / 4K gaming',
    image: './imgas/GPU/rtx5080ventus.jpg'
  },
  {
    id: 'arca310eco',
    name: 'Sparkle Intel Arc A310 ECO Low Profile',
    price: 1479,
    url: 'https://www.komplett.no/product/1307942/datautstyr/pc-komponenter/skjermkort/sparkle-intel-arc-a310-eco-low-profile',
    info: 'Compact GPU for office tasks and light gaming at 1080p.',
    type: 'GPU',
    tier: 'entry',
    bestFor: 'Office / light 1080p gaming',
    image: './imgas/GPU/arca310eco.jpg'
  },
  {
    id: 'rtx5070trio',
    name: 'MSI GeForce RTX 5070 Gaming Trio OC',
    price: 8458,
    url: 'https://www.komplett.no/product/1320979/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5070-gaming-trio-oc?gad_campaignid=20188016872',
    info: 'Mid-range GPU for smooth 1440p gaming with solid cooling.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1440p gaming',
    image: './imgas/GPU/rtx5070trio.jpg'
  },
  {
    id: 'rtx5060ventusplus',
    name: 'MSI GeForce RTX 5060 Ti VENTUS 2X OC PLUS',
    price: 5759,
    url: '',
    info: 'Mid-range GPU for consistent 1080p/1440p gaming performance.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1080p / 1440p gaming',
    image: './imgas/GPU/rtx5060ventusplus.jpg'
  },
  {
    id: 'rtx5060turf',
    name: 'Anus TUF Gaming GeForce RTX 5060 OC',
    price: 5390,
    url: 'https://www.komplett.no/product/1322947/datautstyr/pc-komponenter/skjermkort/asus-tuf-geforce-rtx-5060-ti-gaming-oc',
    info: 'Mid-range GPU with solid cooling for gaming at 1080p.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1080p gaming',
    image: './imgas/GPU/rtx5060turf.jpg'
  },
  {
    id: 'rtx5090suprim',
    name: 'MSI GeSpotForce RTX 5090 SUPRIM LIQUID SUCKER',
    price: 35606,
    url: 'https://www.komplett.no/product/1319422/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5090-suprim-soc?gad_campaignid=20188016872',
    info: 'Extreme high-end GPU with liquid cooling for top-tier performance.',
    type: 'GPU',
    tier: 'enthusiast',
    bestFor: 'Ultimate gaming / workstation',
    image: './imgas/GPU/rtx5090suprim.jpg'
  },
  {
    id: 'rtx5070phoenix',
    name: 'Gainward GeForce RTX 5070 Ti Phoenix-S GS',
    price: 11113,
    url: '',
    info: 'High-performance GPU for smooth 1440p and 4K gaming.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: '1440p / 4K gaming',
    image: './imgas/GPU/rtx5070phoenix.jpg'
  },
  {
    id: 'rtx5060ghost',
    name: 'Gainward GeForce RTX 5060 Ti Ghost',
    price: 4890,
    url: 'https://www.komplett.no/product/1324963/datautstyr/pc-komponenter/skjermkort/gainward-geforce-rtx-5070-ti-phoenix-s-gs?gad_campaignid=20188016872',
    info: 'Mid-range GPU for reliable 1080p and light 1440p gaming.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1080p / 1440p gaming',
    image: './imgas/GPU/rtx5060ghost.jpg'
  },
  {
    id: 'rtx5070ventus',
    name: 'MSI GeForce RTX 5070 Ventus 2X OC',
    price: 6480,
    url: 'https://www.komplett.no/product/1320975/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5070-ventus-2x-oc-hvit?gad_campaignid=20188016872',
    info: 'Mid-range GPU for smooth 1440p gaming and content creation.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1440p gaming / content creation',
    image: './imgas/GPU/rtx5070ventuswhite.jpg'
  },
  {
    id: 'rx9070quicksilver',
    name: 'XFX Quicksilver AMD Radeon RX 9070 XT Magnetic Air (sort)',
    price: 8990,
    url: 'https://www.komplett.no/product/1321210/datautstyr/pc-komponenter/skjermkort/xfx-quicksilver-amd-radeon-rx-9070-xt-gaming-hvit?gad_campaignid=1601331773',
    info: 'High-end AMD GPU with efficient cooling for 1440p/4K gaming.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: '1440p / 4K gaming',
    image: './imgas/GPU/rx9070quicksilver.jpg'
  },
  {
    id: 'rtx3050pegasus',
    name: 'Gainward GeForce RTX 3050 Pegasus',
    price: 2349,
    url: 'https://www.komplett.no/product/1205505/datautstyr/pc-komponenter/skjermkort/gainward-geforce-rtx-3050-pegasus?gad_campaignid=20188016872',
    info: 'Entry-level GPU ideal for 1080p gaming and budget builds.',
    type: 'GPU',
    tier: 'entry',
    bestFor: '1080p gaming / budget builds',
    image: './imgas/GPU/rtx3050pegasus.jpg'
  },
  {
    id: 'rtx5060ventusplus2',
    name: 'MSI GeForce RTX 5060 Ti VENTUS 2X OC PLUS',
    price: 4080,
    url: 'https://www.komplett.no/product/1323042/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5060-ti-ventus-2x-oc-plus?gad_campaignid=20188016872',
    info: 'Mid-range GPU for consistent 1080p and 1440p performance.',
    type: 'GPU',
    tier: 'mid-range',
    bestFor: '1080p / 1440p gaming',
    image: './imgas/GPU/rtx5060ventusplus2.jpg'
  },
  {
    id: 'rx9070mercury',
    name: 'XFX Mercury AMD Radeon RX 9070 XT OC Gaming RGB (sort)',
    price: 9713,
    url: '',
    info: 'High-end AMD GPU with RGB lighting for 1440p/4K gaming.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: '1440p / 4K gaming',
    image: './imgas/GPU/rx9070mercury.jpg'
  },
  {
    id: 'rx9070hellhound',
    name: 'PowerColor Hellhound AMD Radeon RX 9070 XT (sort)',
    price: 9969,
    url: 'https://www.komplett.no/product/1321424/datautstyr/pc-komponenter/skjermkort/powercolor-hellhound-amd-radeon-rx-9070-xt-sort?gad_campaignid=20188016872',
    info: 'High-end AMD GPU suitable for 1440p and 4K gaming.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: '1440p / 4K gaming',
    image: './imgas/GPU/rx9070hellhound.jpg'
  },
  {
    id: 'rx9070magnetic',
    name: 'XFX Mercury AMD Radeon RX 9070 XT OC Magnetic Air RGB (hvit)',
    price: 10454,
    url: 'https://www.komplett.no/product/1321217/datautstyr/pc-komponenter/skjermkort/xfx-quicksilver-amd-radeon-rx-9070-xt-magnetic-air-hvit',
    info: 'High-end AMD GPU with advanced cooling and RGB lighting.',
    type: 'GPU',
    tier: 'high-end',
    bestFor: '1440p / 4K gaming',
    image: './imgas/GPU/rx9070magnetic.jpg'
  },
  {
    id: 'rtx5090tuf',
    name: 'ASUS TUF Gaming GeForce RTX 5090 OC',
    price: 29989,
    url: 'https://www.komplett.no/product/1319469/datautstyr/pc-komponenter/skjermkort/asus-tuf-gaming-geforce-rtx-5090-oc?gad_campaignid=20188016872',
    info: 'Top-tier GPU with robust cooling for extreme 4K gaming.',
    type: 'GPU',
    tier: 'enthusiast',
    bestFor: 'Ultimate gaming / workstation',
    image: './imgas/GPU/rtx5090tuf.jpg'
  },
  {
    id: 'rtx3050lp',
    name: 'MSI GeForce RTX 3050 LP OC',
    price: 2478,
    url: 'https://www.komplett.no/product/1304035/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-3050-lp-oc',
    info: 'Entry-level low-profile GPU for compact builds and 1080p gaming.',
    type: 'GPU',
    tier: 'entry',
    bestFor: 'Compact 1080p builds',
    image: './imgas/GPU/rtx3050lp.jpg'
  }
];
