const storage = [
  {
    id: 'nvme-500gb',
    name: 'Kingston NV3 SSD 2TB',
    price: 1311,
    url: 'https://www.komplett.no/product/1311276/datautstyr/lagring/harddiskerssd/ssd-m2/kingston-nv3-ssd-2tb',
    info: '2TB NVMe SSD with fast read/write speeds for gaming and general use.',
    type: 'NVMe',
    tier: 'mid-range',
    bestFor: 'Gaming PCs and high-speed storage',
    image: './imgas/Storege/nvme-500gb.jpg'
  },
  {
    id: 'nvme-1tb',
    name: 'Kingston KC3000 M.2 2280 NVMe SSD 2TB',
    price: 1834,
    url: 'https://www.komplett.no/product/1201336/datautstyr/lagring/harddiskerssd/ssd-m2/kingston-kc3000-m2-2280-nvme-ssd-2tb',
    info: 'High-performance NVMe SSD with excellent durability and speed.',
    type: 'NVMe',
    tier: 'mid-range',
    bestFor: 'Gaming PCs, content creation, and fast storage needs',
    image: './imgas/Storege/nvme'
  },
  {
    id: 'nvme-4tb',
    name: 'Kingston FURY Renegade M.2 NVME SSD HeatS 4TB',
    price: 4499,
    url: 'https://www.komplett.no/product/1220152/datautstyr/lagring/harddiskerssd/ssd-m2/kingston-fury-renegade-m2-nvme-ssd-heats-4tb',
    info: '4TB NVMe SSD with heatsink, ideal for sustained high-speed workloads.',
    type: 'NVMe',
    tier: 'high-end',
    bestFor: 'Enthusiast gaming PCs and workstation storage',
    image: './imgas/Storege/nvme-4tb.jpg'
  },
  {
    id: 'samgsung-2tb',
    name: 'Samsung 990 PRO NVMe M.2 SSD Heatsink 2TB',
    price: 2149,
    url: 'https://www.komplett.no/product/1253103/datautstyr/lagring/harddiskerssd/ssd-m2/samsung-990-pro-nvme-m2-ssd-heatsink-2tb',
    info: '2TB NVMe SSD with heatsink, excellent for high-speed and heavy-load tasks.',
    type: 'NVMe',
    tier: 'high-end',
    bestFor: 'Gaming PCs and high-speed data storage',
    image: './imgas/Storege/samgsung-2tb.jpg'
  },
  {
    id: 'KC3000-1tb',
    name: 'Kingston KC3000 M.2 2280 NVMe SSD 1TB',
    price: 1098,
    url: 'https://www.komplett.no/product/1201337/datautstyr/lagring/harddiskerssd/ssd-m2/kingston-kc3000-m2-2280-nvme-ssd-1tb',
    info: '1TB SATA SSD with reliable speed and solid performance for general use.',
    type: 'SATA',
    tier: 'budget',
    bestFor: 'Entry to mid-range PCs and general storage',
    image: './imgas/Storege/KC3000-1tb.jpg'
  },
  {
    id: 'kingston-1tb',
    name: 'Kingston NV3 SSD 1TB',
    price: 689,
    url: 'https://www.komplett.no/product/1311274/datautstyr/lagring/harddiskerssd/ssd-m2/kingston-nv3-ssd-1tb',
    info: '1TB SATA SSD, budget-friendly with reliable performance for everyday use.',
    type: 'SATA',
    tier: 'budget',
    bestFor: 'Basic gaming and office PCs',
    image: './imgas/Storege/kingston-1tb.jpg'
  },
  {
    id: 'play2tb',
    name: 'Kingston FURY Renegade M.2 2280 SSD 1TB',
    price: 1190,
    url: 'https://www.komplett.no/product/1220153/datautstyr/lagring/harddiskerssd/ssd-m2/kingston-fury-renegade-m2-2280-ssd-1tb',
    info: '1TB SATA SSD with good durability and speed for general applications.',
    type: 'SATA',
    tier: 'mid-range',
    bestFor: 'Mid-range PCs and light content creation',
    image: './imgas/Storege/play2tb.jpg'
  },
  {
    id: 'fury-2tb',
    name: 'Kingston FURY Renegade M.2 2280 SSD 2TB',
    price: 1988,
    url: 'https://www.komplett.no/product/1220154/datautstyr/lagring/harddiskerssd/ssd-m2/kingston-fury-renegade-m2-2280-ssd-2tb',
    info: '2TB HDD-style storage solution offering solid performance and capacity for gaming.',
    type: 'HDD',
    tier: 'mid-range',
    bestFor: 'Gaming PCs needing large storage',
    image: './imgas/Storege/fury-2tb.jpg'
  },
  {
    id: 'WDSN850X-1tb',
    name: 'WD Black SN850X NVMe SSD 1TB',
    price: 1229,
    url: 'https://www.komplett.no/product/1217371/datautstyr/lagring/harddiskerssd/ssd-m2/wd-black-sn850x-nvme-ssd-1tb',
    info: 'High-speed NVMe SSD with 1TB capacity, excellent for modern games.',
    type: 'HDD',
    tier: 'mid-range',
    bestFor: 'Gaming and productivity PCs',
    image: './imgas/Storege/WDSN850X-1tb.jpg'
  },
  {
    id: 'WDSN850X-4tb',
    name: 'WD Black SN850X NVMe SSD 4TB',
    price: 4990,
    url: 'https://www.komplett.no/product/1217369/datautstyr/lagring/harddiskerssd/ssd-m2/wd-black-sn850x-nvme-ssd-4tb',
    info: '4TB NVMe SSD for high-speed, large storage needs.',
    type: 'HDD',
    tier: 'high-end',
    bestFor: 'High-end gaming rigs and content creators',
    image: './imgas/Storege/WDSN850X-4tb.jpg'
  },
  {
    id: 'kingston-500gbblue',
    name: 'Kingston NV3 SSD 500gb',
    price: 473,
    url: 'https://www.komplett.no/product/1311269/datautstyr/lagring/harddiskerssd/ssd-m2/kingston-nv3-ssd-500gb',
    info: '500GB NVMe SSD, small capacity but fast read/write speeds.',
    type: 'NVMe',
    tier: 'budget',
    bestFor: 'Entry-level PCs or boot drive',
    image: './imgas/Storege/kingston-500gbblue.jpg'
  },
  {
    id: 'v-nandssd-1tb',
    name: 'Samsung 990 PRO NVMe M.2 SSD 1TB',
    price: 1249,
    url: 'https://www.komplett.no/product/1220537/datautstyr/lagring/harddiskerssd/ssd-m2/samsung-990-pro-nvme-m2-ssd-1tb',
    info: '1TB high-performance NVMe SSD for fast storage and gaming.',
    type: 'NVMe',
    tier: 'mid-range',
    bestFor: 'Gaming PCs and fast boot drives',
    image: './imgas/Storege/v-nandssd-1tb.jpg'
  },
  {
    id: 'furryrenegade-4tb',
    name: 'Kingston FURY Renegade G5 PCIe 5.0 NVMe M.2 SSD 4TB',
    price: 7390,
    url: 'https://www.komplett.no/product/1324397/datautstyr/lagring/harddiskerssd/ssd-m2/kingston-fury-renegade-g5-pcie-50-nvme-m2-ssd-4tb',
    info: '4TB PCIe 5.0 NVMe SSD for extreme speed and high-end storage.',
    type: 'NVMe',
    tier: 'premium',
    bestFor: 'High-end gaming and workstation builds',
    image: './imgas/Storege/furryrenegade-4tb.jpg'
  },
  {
    id: 'mp600-1tb',
    name: 'Corsair MP600 ELITE 1TB NVMe PCIe M.2 SSD',
    price: 1190,
    url: 'https://www.komplett.no/product/1303677',
    info: '1TB NVMe SSD offering excellent speeds for gaming and productivity.',
    type: 'NVMe',
    tier: 'mid-range',
    bestFor: 'Gaming PCs and general high-speed storage',
    image: './imgas/Storege/mp600-1tb.jpg'
  },
  {
    id: 'mp600-2tbxt',
    name: 'Corsair MP600 CORE XT NVMe PCIe M.2 SSD 2TB',
    price: 1764,
    url: 'https://www.komplett.no/product/1323874/datautstyr/lagring/harddiskerssd/ssd-m2/corsair-mp600-core-xt-nvme-pcie-m2-ssd-2tb',
    info: '2TB SATA SSD with solid speed for gaming and general storage.',
    type: 'SATA',
    tier: 'mid-range',
    bestFor: 'Gaming PCs and general storage',
    image: './imgas/Storege/mp600-2tbxt.jpg'
  },
  {
    id: 'mp600-8tbNH',
    name: 'Corsair MP600 PRO NH NVMe M.2 SSD 8TB',
    price: 11754,
    url: 'https://www.komplett.no/product/1221581/datautstyr/lagring/harddiskerssd/ssd-m2/corsair-mp600-pro-nh-nvme-m2-ssd-8tb',
    info: '8TB high-capacity SATA SSD for extreme storage and fast performance.',
    type: 'SATA',
    tier: 'premium',
    bestFor: 'Workstations and data-heavy setups',
    image: './imgas/Storege/mp600-8tbNH.jpg'
  },
  {
    id: 'kc3000-512gb',
    name: 'Kingston KC3000 M.2 2280 NVMe SSD 512GB',
    price: 739,
    url: 'https://www.komplett.no/product/1201339/datautstyr/lagring/harddiskerssd/ssd-m2/kingston-kc3000-m2-2280-nvme-ssd-512gb',
    info: '512GB HDD for basic storage and backup solutions.',
    type: 'HDD',
    tier: 'budget',
    bestFor: 'Entry-level PCs and backups',
    image: './imgas/Storege/KC3000-512gb.jpg'
  },
  {
    id: 'kingston-4tbblue',
    name: 'Kingston NV3 SSD 4TB',
    price: 2879,
    url: 'https://www.komplett.no/product/1311271/datautstyr/lagring/harddiskerssd/ssd-m2/kingston-nv3-ssd-4tb',
    info: '4TB HDD with large storage for mass media and general files.',
    type: 'HDD',
    tier: 'high-end',
    bestFor: 'Content storage and gaming libraries',
    image: ''
  },
  {
    id: 'hdd-8tb',
    name: 'WD Black SN850X NVMe SSD 2TB',
    price: 2190,
    url: 'https://www.komplett.no/product/1217368/datautstyr/lagring/harddiskerssd/ssd-m2/wd-black-sn850x-nvme-ssd-2tb',
    info: '2TB HDD for reliable and large-capacity storage.',
    type: 'HDD',
    tier: 'high-end',
    bestFor: 'Gaming PCs and backup storage',
    image: './imgas/Storege/hdd-8tb.jpg'
  },
  {
    id: 'WDblakck-2tb',
    name: 'WD Black SN850X Heatsink NVMe SSD 2TB',
    price: 2759,
    url: 'https://www.komplett.no/product/1217370/datautstyr/lagring/harddiskerssd/ssd-m2/wd-black-sn850x-heatsink-nvme-ssd-2tb',
    info: '2TB NVMe SSD with heatsink, high-speed for gaming and productivity.',
    type: 'NVMe',
    tier: 'high-end',
    bestFor: 'Gaming and workstation PCs',
    image: './imgas/Storege/WDblakck-2tb.jpg'
  },
  {
    id: 'Samsung-1tb-heatsink',
    name: 'Samsung 990 PRO NVMe M.2 SSD Heatsink 1TB',
    price: 1408,
    url: 'https://www.komplett.no/product/1253101/datautstyr/lagring/harddiskerssd/ssd-m2/samsung-990-pro-nvme-m2-ssd-heatsink-1tb',
    info: '1TB NVMe SSD with heatsink, reliable for high-speed storage.',
    type: 'NVMe',
    tier: 'mid-range',
    bestFor: 'Gaming PCs and fast boot drives',
    image: './imgas/Storege/Samsung-1tb-heatsink.jpg'
  },
  {
    id: 'WDgreen-1tb',
    name: 'WD Green SN3000 NVMe SSD 1TB',
    price: 671,
    url: 'https://www.komplett.no/product/1324810/datautstyr/lagring/harddiskerssd/ssd-m2/wd-green-sn3000-nvme-ssd-1tb',
    info: '1TB NVMe SSD with moderate speed, affordable option for daily use.',
    type: 'NVMe',
    tier: 'budget',
    bestFor: 'Entry-level PCs and general storage',
    image: './imgas/Storege/WDgreen-1tb.jpg'
  },
  {
    id: 'mp700pro-1tb',
    name: 'Corsair MP700 PRO 1TB NVMe 2.0 M.2 SSD',
    price: 1990,
    url: 'https://www.komplett.no/product/1302034/datautstyr/lagring/harddiskerssd/ssd-m2/corsair-mp700-pro-1tb-nvme-20-m2-ssd',
    info: '1TB SATA SSD for fast storage and gaming needs.',
    type: 'SATA',
    tier: 'mid-range',
    bestFor: 'Gaming PCs and mid-range builds',
    image: './imgas/Storege/MP700-1tb.jpg'
  },
  {
    id: 'wdgreen-500gb',
    name: 'WD Green SN3000 NVMe SSD 500GB',
    price: 415,
    url: 'https://www.komplett.no/product/1324825/datautstyr/lagring/harddiskerssd/ssd-m2/wd-green-sn3000-nvme-ssd-500gb',
    info: '500GB SATA SSD, budget-friendly and reliable for basic storage.',
    type: 'SATA',
    tier: 'budget',
    bestFor: 'Basic PCs and backups',
    image: './imgas/Storege/wdgreen-500gb.jpg'
  },
  {
    id: 'wdblack-1tbsn8100',
    name: 'WD_BLACK SN8100 NVMe SSD 1TB',
    price: 2390,
    url: 'https://www.komplett.no/product/1324824/datautstyr/lagring/harddiskerssd/ssd-m2/wdblack-sn8100-nvme-ssd-1tb',
    info: '1TB HDD for large storage, good for general usage.',
    type: 'HDD',
    tier: 'mid-range',
    bestFor: 'Gaming PCs and general storage',
    image: './imgas/Storege/wdblack-1tbsn8100.jpg'
  },
  {
    id: 'play-4tb',
    name: 'WD Black SN850P NVMe SSD 4TB',
    price: 4990,
    url: 'https://www.komplett.no/product/1328576/datautstyr/lagring/harddiskerssd/ssd-m2/wd-black-sn850p-nvme-ssd-4tb',
    info: '4TB HDD for heavy storage and backups.',
    type: 'HDD',
    tier: 'high-end',
    bestFor: 'Gaming PCs, media libraries, and backups',
    image: './imgas/Storege/play-4tb.jpg'
  },
  {
    id: 'play-8tb',
    name: 'WD Black SN850P NVMe SSD 8TB',
    price: 10999,
    url: 'https://www.komplett.no/product/1328575/datautstyr/lagring/harddiskerssd/ssd-m2/wd-black-sn850p-nvme-ssd-8tb',
    info: '8TB NVMe SSD for massive high-speed storage.',
    type: 'NVMe',
    tier: 'premium',
    bestFor: 'High-end workstations and gaming PCs',
    image: ''
  },
  {
    id: 'mp700elite-1tb',
    name: 'Corsair MP700 Elite 1TB',
    price: 1728,
    url: 'https://www.komplett.no/product/1319159/datautstyr/lagring/harddiskerssd/ssd-m2/corsair-mp700-elite-1tb',
    info: '1TB SATA SSD, reliable and fast for general use and gaming.',
    type: 'SATA',
    tier: 'mid-range',
    bestFor: 'Gaming and productivity PCs',
    image: ''
  },
  {
    id: 'sata-1tb-3',
    name: 'WD Black SN770M NVMe 1TB',
    price: 1490,
    url: 'https://www.komplett.no/product/1252257/datautstyr/lagring/harddiskerssd/ssd-m2/wd-green-sn350-nvme-2tb',
    info: '1TB SATA SSD with solid performance for mid-range systems.',
    type: 'SATA',
    tier: 'mid-range',
    bestFor: 'Gaming PCs and general storage',
    image: ''
  },
  {
    id: 'nvme-2tb-4',
    name: 'WD Green SN350 NVMe 1TB',
    price: 769,
    url: 'https://www.komplett.no/product/1252258/datautstyr/lagring/harddiskerssd/ssd-m2/wd-black-sn850p-nvme-2tb',
    info: '1TB NVMe SSD with moderate speed, budget-friendly option.',
    type: 'NVMe',
    tier: 'budget',
    bestFor: 'Entry-level PCs and fast storage',
    image: './imgas/Storege/play2tb.jpg'
  },
  {
    id: 'wdblack-2tb-sn770m',
    name: 'WD Black SN770M NVMe 2TB',
    price: 2456,
    url: 'https://www.komplett.no/product/1252256/datautstyr/lagring/harddiskerssd/ssd-m2/wd-green-sn350-nvme-1tb',
    info: '2TB NVMe SSD with excellent speed and reliability.',
    type: 'NVMe',
    tier: 'high-end',
    bestFor: 'Gaming PCs and workstation storage',
    image: '.imgas/Storege/wdblack-2tb-sn770m.jpg'
  },
  {
    id: 'playwd-1tb-sn850p',
    name: 'WD Green SN850p NVMe 1TB',
    price: 1513,
    url: 'https://www.komplett.no/product/1250136/datautstyr/lagring/harddiskerssd/ssd-m2/wd-black-sn850p-nvme-1tb',
    info: '1TB NVMe SSD with moderate speed, affordable option for daily use.',
    type: 'NVMe',
    tier: 'mid-range',
    bestFor: 'Entry-level PCs and general storage',
    image: '.imgas/Storege/playwd-1tb-sn850p.jpg'
  }
];
