const psu = [
  {
    id: 'asus-tuf-gaming-850w-gold-psu',
    name: 'ASUS TUF Gaming 850W Gold PSU',
    price: 1490,
    url: 'https://www.komplett.no/product/1218392/datautstyr/pc-komponenter/stroemforsyning/enheter/asus-tuf-gaming-850w-gold-psu',
    info: 'Reliable 850W PSU with 80+ Gold efficiency, perfect for high-end gaming builds.',
    type: 'gold',
    tier: 'budget',
    bestFor: 'High-end gaming PCs with single GPU',
    image: '/imgas/PSU/asus-tuf-gaming-850w-gold-psu.jpg'
  },
  {
    id: 'corsair-rmx-series-rm750x-psu',
    name: 'Corsair RMx Series RM750x PSU',
    price: 1769,
    url: 'https://www.komplett.no/product/1309146/datautstyr/pc-komponenter/stroemforsyning/enheter/corsair-rmx-series-rm750x-psu',
    info: '750W fully modular PSU, 80+ Gold certified, silent operation.',
    type: 'gold',
    tier: 'mid-range',
    bestFor: 'Gaming and streaming PCs with moderate GPU load',
    image: '/imgas/PSU/corsair-rmx-series-rm750x-psu.jpg'
  },
  {
    id: 'phanteks-amp-gh-komplett-edition-1200w-80-platinum-psu',
    name: 'Phanteks AMP GH Komplett Edition 1200W 80+ Platinum PSU',
    price: 2799,
    url: 'https://www.komplett.no/product/1246889/datautstyr/pc-komponenter/stroemforsyning/enheter/phanteks-amp-gh-komplett-edition-1200w-80-platinum-psu',
    info: 'High-efficiency 1200W PSU with 80+ Platinum certification, great for multi-GPU setups.',
    type: '',
    tier: 'high-end',
    bestFor: 'Enthusiast gaming rigs and content creation PCs',
    image: '/imgas/PSU/phanteks-amp-gh-komplett-edition-1200w-80-platinum-psu.jpg'
  },
  {
    id: 'asus-tuf-gaming-1000w-gold-psu',
    name: 'ASUS TUF Gaming 1000W Gold PSU',
    price: 1990,
    url: 'https://www.komplett.no/product/1218388/datautstyr/pc-komponenter/stroemforsyning/enheter/asus-tuf-gaming-1000w-gold-psu',
    info: '1000W PSU with stable power delivery and 80+ Gold efficiency.',
    type: '',
    tier: 'mid-range',
    bestFor: 'High-performance gaming PCs with one or two GPUs',
    image: '/imgas/PSU/asus-tuf-gaming-1000w-gold-psu.jpg'
  },
  {
    id: 'asus-tuf-gaming-750w-gold-psu',
    name: 'ASUS TUF Gaming 750W Gold PSU',
    price: 1349,
    url: 'https://www.komplett.no/product/1218393/datautstyr/pc-komponenter/stroemforsyning/enheter/asus-tuf-gaming-750w-gold-psu',
    info: '750W Gold PSU, reliable for gaming builds without overkill.',
    type: '',
    tier: 'budget',
    bestFor: 'Mid-range gaming PCs',
    image: '/imgas/PSU/asus-tuf-gaming-750w-gold-psu.jpg'
  },
  {
    id: 'asus-tuf-gaming-1200w-gold-psu',
    name: 'ASUS TUF Gaming 1200W Gold PSU',
    price: 2758,
    url: 'https://www.komplett.no/product/1246021/datautstyr/pc-komponenter/stroemforsyning/enheter/asus-tuf-gaming-1200w-gold-psu',
    info: '1200W PSU, high reliability and efficiency for demanding systems.',
    type: '',
    tier: 'high-end',
    bestFor: 'High-end gaming rigs and workstation PCs',
    image: '/imgas/PSU/asus-tuf-gaming-1200w-gold-psu.jpg'
  },
  {
    id: 'phanteks-amp-gh-komplett-edition-1000w-80-platinum-psu',
    name: 'Phanteks AMP GH Komplett Edition 1000W 80+ Platinum PSU',
    price: 2199,
    url: 'https://www.komplett.no/product/1246890/datautstyr/pc-komponenter/stroemforsyning/enheter/phanteks-amp-gh-komplett-edition-1000w-80-platinum-psu',
    info: '1000W Platinum PSU for high-performance builds and stable multi-GPU setups.',
    type: '',
    tier: 'mid-range',
    bestFor: 'Gaming PCs with multiple GPUs or overclocked CPUs',
    image: '/imgas/PSU/phanteks-amp-gh-komplett-edition-1000w-80-platinum-psu.jpg'
  },
  {
    id: 'msi-mag-a750gl-pcie5-750w-psu',
    name: 'MSI MAG A750GL PCIE5 750W PSU',
    price: 1315,
    url: 'https://www.komplett.no/product/1246512/datautstyr/pc-komponenter/stroemforsyning/enheter/msi-mag-a750gl-pcie5-750w-psu',
    info: 'Affordable 750W PSU with PCIe5 compatibility, ideal for mid-range gaming.',
    type: '',
    tier: 'budget',
    bestFor: 'Mid-range gaming PCs',
    image: '/imgas/PSU/msi-mag-a750gl-pcie5-750w-psu.jpg'
  },
  {
    id: 'msi-mag-a650gl-650w-psu',
    name: 'MSI MAG A650GL 650W PSU',
    price: 1190,
    url: 'https://www.komplett.no/product/1246513/datautstyr/pc-komponenter/stroemforsyning/enheter/msi-mag-a650gl-650w-psu',
    info: 'Compact 650W PSU for budget builds with stable power delivery.',
    type: '',
    tier: 'budget',
    bestFor: 'Entry-level gaming PCs',
    image: '/imgas/PSU/msi-mag-a650gl-650w-psu.jpg'
  },
  {
    id: 'msi-mag-a850gl-pcie5-850w-psu',
    name: 'MSI MAG A850GL PCIE5 850W PSU',
    price: 1745,
    url: 'https://www.komplett.no/product/1246511/datautstyr/pc-komponenter/stroemforsyning/enheter/msi-mag-a850gl-pcie5-850w-psu',
    info: 'Reliable 850W PSU with PCIe5 support for modern mid-range builds.',
    type: '',
    tier: 'mid-range',
    bestFor: 'Gaming PCs with one high-end GPU',
    image: '/imgas/PSU/msi-mag-a850gl-pcie5-850w-psu.jpg'
  },
  {
    id: 'cooler-master-mwe-gold-650w-v2-psu',
    name: 'Cooler Master MWE Gold 650W V2 PSU',
    price: 1290,
    url: 'https://www.komplett.no/product/1176418/datautstyr/pc-komponenter/stroemforsyning/enheter/cooler-master-mwe-gold-650w-v2-psu',
    info: '650W Gold-certified PSU, budget-friendly with stable power.',
    type: '',
    tier: 'budget',
    bestFor: 'Entry-level to mid-range gaming PCs',
    image: '/imgas/PSU/cooler-master-mwe-gold-650w-v2-psu.jpg'
  },
  {
    id: 'corsair-rmx-series-rm850x-psu',
    name: 'Corsair RMx Series RM850x PSU',
    price: 1999,
    url: 'https://www.komplett.no/product/1309150/datautstyr/pc-komponenter/stroemforsyning/enheter/corsair-rmx-series-rm850x-psu?queryid=213696c4e0234ccb58e388db1b20896e&sort=None',
    info: '850W fully modular PSU, 80+ Gold, excellent for overclocked systems.',
    type: '',
    tier: 'mid-range',
    bestFor: 'High-performance gaming PCs',
    image: '/imgas/PSU/corsair-rmx-series-rm850x-psu.jpg'
  },
  {
    id: 'corsair-rme-series-rm750e-psu-white',
    name: 'Corsair RMe Series RM750e PSU (hvit)',
    price: 1444,
    url: 'https://www.komplett.no/product/1322272/datautstyr/pc-komponenter/stroemforsyning/enheter/corsair-rme-series-rm750e-psu-hvit',
    info: '750W budget-friendly PSU with reliable efficiency and quiet operation.',
    type: '',
    tier: 'budget',
    bestFor: 'Mid-range gaming PCs',
    image: '/imgas/PSU/corsair-rme-series-rm750e-psu-white.jpg'
  },
  {
    id: 'corsair-rme-series-rm850e-psu-black',
    name: 'Corsair RMe Series RM850e PSU (sort)',
    price: 1676,
    url: 'https://www.komplett.no/product/1317195/datautstyr/pc-komponenter/stroemforsyning/enheter/corsair-rme-series-rm850e-psu-sort',
    info: '850W PSU, fully modular, reliable and quiet for gaming setups.',
    type: '',
    tier: 'mid-range',
    bestFor: 'Gaming PCs with one GPU',
    image: '/imgas/PSU/corsair-rme-series-rm850e-psu-black.jpg'
  },
  {
    id: 'asus-rog-loki-sfx-l-1000w-psu',
    name: 'ASUS ROG Loki SFX-L 1000W PSU',
    price: 3390,
    url: 'https://www.komplett.no/product/1218408/datautstyr/pc-komponenter/stroemforsyning/enheter/asus-rog-loki-sfx-l-1000w-psu',
    info: 'Compact SFX-L 1000W PSU with high efficiency for small form-factor builds.',
    type: '',
    tier: 'high-end',
    bestFor: 'Mini-ITX high-end gaming PCs',
    image: '/imgas/PSU/asus-rog-loki-sfx-l-1000w-psu.jpg'
  },
  {
    id: 'asus-rog-strix-850w-platinum-psu',
    name: 'Asus ROG Strix 850W Platinum PSU',
    price: 2668,
    url: 'https://www.komplett.no/product/1316489/datautstyr/pc-komponenter/stroemforsyning/enheter/asus-rog-strix-850w-platinum-psu',
    info: 'High-efficiency 850W Platinum PSU, excellent for overclocked systems.',
    type: '',
    tier: 'high-end',
    bestFor: 'High-end gaming PCs and content creation rigs',
    image: '/imgas/PSU/asus-rog-strix-850w-platinum-psu.jpg'
  },
  {
    id: 'msi-meg-ai1300p-pcie5-1300w-psu',
    name: 'MSI MEG AI1300P PCIE5 1300W PSU',
    price: 4155,
    url: 'https://www.komplett.no/product/1221881/datautstyr/pc-komponenter/stroemforsyning/enheter/msi-meg-ai1300p-pcie5-1300w-psu',
    info: '1300W premium PSU with PCIe5 support, ideal for multi-GPU setups.',
    type: '',
    tier: 'premium',
    bestFor: 'High-end gaming and workstation PCs',
    image: '/imgas/PSU/msi-meg-ai1300p-pcie5-1300w-psu.jpg'
  },
  {
    id: 'asus-rog-loki-sfx-l-850w-psu',
    name: 'ASUS ROG Loki SFX-L 850W PSU',
    price: 2490,
    url: 'https://www.komplett.no/product/1218404/datautstyr/pc-komponenter/stroemforsyning/enheter/asus-rog-loki-sfx-l-850w-psu',
    info: 'Compact 850W SFX-L PSU with high efficiency, perfect for small builds.',
    type: '',
    tier: 'high-end',
    bestFor: 'Mini-ITX gaming PCs',
    image: '/imgas/PSU/asus-rog-loki-sfx-l-850w-psu.jpg'
  },
  {
    id: 'corsair-ax1600i-1600w-psu',
    name: 'Corsair AX1600i 1600W PSU',
    price: 6649,
    url: 'https://www.komplett.no/product/979698/datautstyr/pc-komponenter/stroemforsyning/enheter/corsair-ax1600i-1600w-psu',
    info: 'Top-tier 1600W PSU, Platinum efficiency, fully modular for extreme setups.',
    type: '',
    tier: 'premium',
    bestFor: 'Extreme high-end gaming rigs and workstations',
    image: '/imgas/PSU/corsair-ax1600i-1600w-psu.jpg'
  },
  {
    id: 'corsair-sf-series-sf1000-80-plus-platinum-sfx-psu',
    name: 'Corsair SF Series SF1000 80 PLUS Platinum SFX PSU',
    price: 2725,
    url: 'https://www.komplett.no/product/1309149/datautstyr/pc-komponenter/stroemforsyning/enheter/corsair-sf-series-sf1000-80-plus-platinum-sfx-psu',
    info: '1000W SFX Platinum PSU, compact and reliable for mini builds.',
    type: '',
    tier: 'high-end',
    bestFor: 'Mini-ITX gaming PCs and compact workstations',
    image: '/imgas/PSU/corsair-sf-series-sf1000-80-plus-platinum-sfx-psu.jpg'
  },
  {
    id: 'be-quiet-pure-power-12-650w-psu',
    name: 'be quiet! PURE POWER 12 650W PSU',
    price: 2148,
    url: 'https://www.komplett.no/product/1316799/datautstyr/pc-komponenter/stroemforsyning/enheter/be-quiet-pure-power-12-650w-psu',
    info: 'Reliable 650W PSU with quiet operation, budget-friendly.',
    type: '',
    tier: 'budget',
    bestFor: 'Entry-level gaming PCs',
    image: '/imgas/PSU/be-quiet-pure-power-12-650w-psu.jpg'
  },
  {
    id: 'corsair-hxi-series-hx1000i-1000w-psu',
    name: 'Corsair HXi Series HX1000i 1000W PSU',
    price: 3083,
    url: 'https://www.komplett.no/product/1245631/datautstyr/pc-komponenter/stroemforsyning/enheter/corsair-hxi-series-hx1000i-1000w-psu',
    info: '1000W fully modular PSU, 80+ Platinum efficiency, stable and quiet.',
    type: '',
    tier: 'high-end',
    bestFor: 'High-end gaming and workstation PCs',
    image: '/imgas/PSU/corsair-hxi-series-hx1000i-1000w-psu.jpg'
  },
  {
    id: 'corsair-rme-series-rm1000e-psu-black',
    name: 'Corsair RMe Series RM1000e PSU (sort)',
    price: 2148,
    url: 'https://www.komplett.no/product/1317197/datautstyr/pc-komponenter/stroemforsyning/enheter/corsair-rme-series-rm1000e-psu-sort',
    info: '1000W PSU with reliable power delivery, suitable for overclocked setups.',
    type: '',
    tier: 'mid-range',
    bestFor: 'High-performance gaming PCs',
    image: '/imgas/PSU/corsair-rme-series-rm1000e-psu-black.jpg'
  },
  {
    id: 'corsair-rme-series-rm1000e-psu-white',
    name: 'Corsair RMe Series RM1000e PSU (hvit)',
    price: 2199,
    url: 'https://www.komplett.no/product/1322274/datautstyr/pc-komponenter/stroemforsyning/enheter/corsair-rme-series-rm1000e-psu-hvit',
    info: '1000W PSU, fully modular, stable and efficient for high-end builds.',
    type: '',
    tier: 'mid-range',
    bestFor: 'High-performance gaming PCs',
    image: '/imgas/PSU/corsair-rme-series-rm1000e-psu-white.jpg'
  },
  {
    id: 'be-quiet-pure-power-12-550w-psu',
    name: 'be quiet! PURE POWER 12 550W PSU',
    price: 1099,
    url: 'https://www.komplett.no/product/1316825/datautstyr/pc-komponenter/stroemforsyning/enheter/be-quiet-pure-power-12-550w-psu',
    info: '550W budget PSU with quiet operation and reliable performance.',
    type: '',
    tier: 'budget',
    bestFor: 'Entry-level gaming PCs',
    image: '/imgas/PSU/be-quiet-pure-power-12-550w-psu.jpg'
  },
  {
    id: 'be-quiet-pure-power-12-1000w-psu',
    name: 'be quiet! PURE POWER 12 1000W PSU',
    price: 1899,
    url: 'https://www.komplett.no/product/1316796/datautstyr/pc-komponenter/stroemforsyning/enheter/be-quiet-pure-power-12-1000w-psu',
    info: '1000W PSU with quiet operation, ideal for gaming and workstation builds.',
    type: '',
    tier: 'mid-range',
    bestFor: 'High-performance gaming PCs',
    image: '/imgas/PSU/be-quiet-pure-power-12-1000w-psu.jpg'
  },
  {
    id: 'be-quiet-pure-power-12-850w-psu',
    name: 'be quiet! PURE POWER 12 850W PSU',
    price: 1557,
    url: 'https://www.komplett.no/product/1316820/datautstyr/pc-komponenter/stroemforsyning/enheter/be-quiet-pure-power-12-850w-psu',
    info: '850W reliable PSU with quiet performance, great for mid to high-end builds.',
    type: '',
    tier: 'mid-range',
    bestFor: 'Gaming PCs with high-end GPU',
    image: '/imgas/PSU/be-quiet-pure-power-12-850w-psu.jpg'
  },
  {
    id: 'be-quiet-pure-power-12-m-850w-psu',
    name: 'be quiet! PURE POWER 12 M 850W PSU',
    price: 1735,
    url: 'https://www.komplett.no/product/1249729/datautstyr/pc-komponenter/stroemforsyning/enheter/be-quiet-pure-power-12-m-850w-psu',
    info: '850W modular PSU, quiet and efficient for high-end gaming PCs.',
    type: '',
    tier: 'mid-range',
    bestFor: 'High-performance gaming and workstation PCs',
    image: '/imgas/PSU/be-quiet-pure-power-12-m-850w-psu.jpg'
  },
  {
    id: 'be-quiet-power-zone-2-750w-psu',
    name: 'be quiet! Power Zone 2 750W PSU',
    price: 1699,
    url: 'https://www.komplett.no/product/1320387/datautstyr/pc-komponenter/stroemforsyning/enheter/be-quiet-power-zone-2-750w-psu',
    info: '750W PSU with solid performance, budget-friendly for gaming PCs.',
    type: '',
    tier: 'mid-range',
    bestFor: 'Mid-range gaming PCs',
    image: '/imgas/PSU/be-quiet-power-zone-2-750w-psu.jpg'
  },
  {
    id: 'asus-prime-850w-gold-psu',
    name: 'Asus Prime 850W Gold PSU',
    price: 1466,
    url: 'https://www.komplett.no/product/1312587/datautstyr/pc-komponenter/stroemforsyning/enheter/asus-prime-850w-gold-psu',
    info: '850W Gold-certified PSU, reliable and efficient for mid-range gaming builds.',
    type: '',
    tier: 'budget',
    bestFor: 'Mid-range gaming PCs',
    image: '/imgas/PSU/asus-prime-850w-gold-psu.jpg'
  },
  {
    id: 'corsair-hx1200i-1200w-psu',
    name: 'Corsair HX1200i 1200W PSU',
    price: 3899,
    url: 'https://www.komplett.no/product/1305544/datautstyr/pc-komponenter/stroemforsyning/enheter/corsair-hx1200i-1200w-psu',
    info: '1200W Platinum PSU, fully modular, ideal for overclocked or multi-GPU setups.',
    type: '',
    tier: 'high-end',
    bestFor: 'High-end gaming and workstation PCs',
    image: '/imgas/PSU/corsair-hx1200i-1200w-psu.jpg'
  },
  {
    id: 'be-quiet-power-zone-2-1000w-psu',
    name: 'be quiet! Power Zone 2 1000W PSU',
    price: 2149,
    url: 'https://www.komplett.no/product/1320389/datautstyr/pc-komponenter/stroemforsyning/enheter/be-quiet-power-zone-2-1000w-psu?queryid=e3671014cb272aaf5984c7315c6cc955&sort=None',
    info: '1000W PSU, reliable and quiet for high-performance gaming and workstation PCs.',
    type: '',
    tier: 'mid-range',
    bestFor: 'High-end gaming PCs',
    image: '/imgas/PSU/be-quiet-power-zone-2-1000w-psu.jpg'
  },
  {
    id: 'be-quiet-dark-power-pro-13-1600w-psu',
    name: 'be quiet! Dark Power Pro 13 1600W PSU',
    price: 5802,
    url: 'https://www.komplett.no/product/1253151/datautstyr/pc-komponenter/stroemforsyning/enheter/be-quiet-dark-power-pro-13-1600w-psu',
    info: '1600W premium PSU, top efficiency and fully modular for extreme systems.',
    type: '',
    tier: 'premium',
    bestFor: 'Extreme high-end gaming rigs and workstations',
    image: '/imgas/PSU/be-quiet-dark-power-pro-13-1600w-psu.jpg'
  },
  {
    id: 'be-quiet-dark-power-pro-13-1300w-psu',
    name: 'be quiet! Dark Power Pro 13 1300W PSU',
    price: 5235,
    url: 'https://www.komplett.no/product/1245622/datautstyr/pc-komponenter/stroemforsyning/enheter/corsair-hxi-series-hx1500i-1500w-psu',
    info: '1300W high-end PSU, Platinum efficiency, fully modular.',
    type: '',
    tier: 'premium',
    bestFor: 'High-end gaming and workstation PCs',
    image: '/imgas/PSU/be-quiet-dark-power-pro-13-1300w-psu.jpg'
  }
];
